#服务启动配置
server:
  port: 8848
#日志文件配置
logging:
  config: classpath:logback-spring.xml
#mybatis-plus配置文件位置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lijjsk.user.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#数据库连接配置
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/wemedia?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Wei20021016
    driver-class-name: com.mysql.cj.jdbc.Driver
